# Generated by Django 2.1.5 on 2022-11-03 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='author',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='img',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(null=True, upload_to='images/question'),
        ),
    ]
