# Generated by Django 2.1.5 on 2022-11-03 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20221103_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 2, 50, 26, 303257), editable=False),
        ),
    ]
