# Generated by Django 2.1.5 on 2022-11-03 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20221103_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_of_questions',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 3, 14, 19, 820408), editable=False),
        ),
    ]
