# Generated by Django 4.1.1 on 2022-11-06 11:18

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 18, 9, 588021), editable=False),
        ),
    ]
