# Generated by Django 2.1.5 on 2022-11-03 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20221103_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 4, 15, 52, 910263), editable=False),
        ),
    ]
